[FixBug] Double Slash when using withSourcePrefix method
laravel-json-api/validation pull request #5
Opened 2021-06-21 12:20 UTC by kbiits

```
public function withSourcePrefix(string $prefix): self
    {
        $prefix = rtrim($prefix, '/');

        $this->withPointers(
            fn($key) => sprintf('%s/%s', $prefix, $this->convertKey($key))
        );
        
        return $this;
    }
```

```
protected function convertKey(string $key): string
    {
        return '/' . str_replace('.', '/', $key);
    }
```

Fix with

```
public function withSourcePrefix(string $prefix): self
    {
        $prefix = rtrim($prefix, '/');

        $this->withPointers(
            fn($key) => sprintf('%s%s', $prefix, $this->convertKey($key))
        );
        
        return $this;
    }
```

2021-06-21 16:13 UTC, lindyhopchris requested changes

2021-06-21 16:13 UTC, lindyhopchris commented on src/ValidatorErrorIterator.php
>          $prefix = rtrim($prefix, '/');
As per my comment in the issue, change this to:

```php
$prefix = trim($prefix, '/');
```

As we want to always ensure it starts with a slash too.

2021-06-21 16:13 UTC, lindyhopchris commented on src/ValidatorErrorIterator.php
> +            fn($key) => sprintf('%s%s', $prefix, $this->convertKey($key))
And then this becomes:

```php
fn($key) => sprintf('/%s%s', $prefix, $this->convertKey($key))
```

2021-06-21 17:35 UTC, kbiits commented on src/ValidatorErrorIterator.php
> +            fn($key) => sprintf('%s%s', $prefix, $this->convertKey($key))
Ok, I'll do it

2021-06-23 12:16 UTC, lindyhopchris approved these changes

2021-06-23 12:17 UTC, merged